### PR TITLE
fix/filter

### PR DESCRIPTION
**Pull request by mosheavni**
filter was not working well

### CODE REVIEW

**Comment by Ramilito** [comment]
Hmm if you don't need an exact match you should be able to send that in as a parameter? 
What's the filter parameter we are trying to  use

**Comment by mosheavni** [comment]
In this case we better use 'string.find' instead of 'string.match'
Cause lua patterns come straight from hell
Previously, filter wouldn't work if you have dashes in your filter term.
string.find(t, string, 1, true) provides a literal search.

**Comment by Ramilito** [comment]
That sounds reasonable and I love the simpler way!
Just make the test run properly, there is a failure here:
image

**Comment by mosheavni** [comment]
> That sounds reasonable and I love the simpler way! Just make the test run properly, there is a failure here: image

fixed, thanks.

**Pull request merged**
