### PR TITLE
feat/add-days-to-years

### PR DESCRIPTION
**Pull request by mosheavni**
I have a resource that's 1 year and 11 months and 2 days
and I see that its age is `1y`
very confusing.
adding days if we specify years

### CODE REVIEW

**Comment by Ramilito** [comment]
I see, wouldn't months be better though?

**Comment by mosheavni** [comment]
> I see, wouldn't months be better though?

I think it would but not all months are same number of days :)

**Comment by Ramilito** [comment]
I feel 500+ days is crazy but I also don't like 1y and 200 days, we used to have it as y/m/d, should we revert to that?

Maybe k9s has a better way?

**Comment by mosheavni** [comment]
Just checked k9s and they do year days
Just like jn this PR
I'll post a screenshot soon

**Comment by mosheavni** [comment]
image
they add days only if it's more than 2 years.
I don't see why not adding days over 1 year.

**Comment by Ramilito** [comment]
I used ti have days here and removed it, needed to be convinced to go back on that 😅 thanks for your patience though 🙏

**Pull request merged**
