### PR TITLE
feat: multiselect actions

### PR DESCRIPTION
**Pull request by Ramilito**
Fixes: #435 

- [x] Act on visually selected lines
- [x] Make getCurrentSelection able to handle both visual and normal
- [ ] Refactor kubectl.kill to reuse the logic between normal and visual binding
- [ ] Investigate other actions we want to do on multirow
- [ ] Make it work for all other resources

### CODE REVIEW

**Comment by mosheavni** [comment]
I wanna give an idea
Instead of visually select and the visual selection could change on every refresh and select different resources, how about "marking" the selected pods maybe with <tab> and adding a mark (just like the port forward symbol) and then if the view refreshes and the order changes, or even when you sort differently, the selection would stay the same!
Nvim-tree is doing something like that with a concept called "bookmarks"
I know this is different that what you started writing but it's far more reliable

**Comment by mosheavni** [comment]
Visual selection is static, the pods can change their location on the table but the visual selection would stay the same since in vim the selection is static, but our views are not static by definition

**Comment by Ramilito** [comment]
Thank you for the feedback and it's ok if already started.
I like your idea, I'll try it out

**Comment by mosheavni** [comment]
If adding a mark to a resource and easily retrieving it after, it could be the best way. I wanna help. I'll try a bit to mess and we can compare results:)

**Comment by Ramilito** [comment]
There is actually something I used to get the sorting to work properly that is using marks in a similar way, check out the utils/marks.lua file

**Pull request closed without merging**
