### PR TITLE
chore: lint commit retrigger

### PR DESCRIPTION
**Pull request by mosheavni**
this commit is intended to retrigger the lint-commit workflow if anything in the PR changes: title, body, reopen, etc.
Right now it only runs when the PR is opened and needs to be manually retriggered after the PR title changes.

### CODE REVIEW

**Comment by mosheavni** [comment]
AAAND it's working! yay

**Review by Ramilito — APPROVED** [review]

**Comment by Ramilito** [comment]
🚀

**Comment by mosheavni** [comment]
I have a struggle understanding why it still fails, but it does retrigger.

**Comment by Ramilito** [comment]
Yeah it expects the format of the commit to be something like the below, I don't plan on it being a blocker for merging but could be fun to have pretty commits:
```
feat: something something
fix: something something
chore: something something

```

**Comment by Ramilito** [comment]
Oh and it also looks at previous commits, saw that your last one was correct

**Pull request merged**
