### PR TITLE
chore: defaulting to all containers when no container is specified

### PR DESCRIPTION
**Pull request by Ramilito**
defaulting to all containers when none is specified
using kubectl for the initial opening of logs view since curl only supports one container per session

### CODE REVIEW

**Comment by mosheavni** [comment]
image
view is not full when following

**Comment by Ramilito** [comment]
Hmmmmm...I'm not seeing that, how did you get that results?

**Comment by mosheavni** [comment]
create this pod:
```
cat <<EOF | kaf -
apiVersion: v1
kind: Pod
metadata:
  name: incrementing-pod
  annotations:
    sidecar.istio.io/inject: "false"

spec:
  containers:
  - name: incrementing-container
    image: alpine
    command: ["/bin/sh", "-c"]
    args:
      - |
        i=0
        while sleep 1; do
          echo hello $i
          i=$((i + 1))
        done

  - name: incrementing-container2
    image: alpine
    command: ["/bin/sh", "-c"]
    args:
      - |
        i=0
        while sleep 1; do
          echo bye $i
          i=$((i + 1))
        done
EOF

```

click `gl` on the pod, then `f` to follow

**Comment by Ramilito** [comment]
Yeah that made sense, adjusted it

**Comment by Ramilito** [comment]
What do you think? merge?

**Comment by mosheavni** [comment]
checking

**Comment by mosheavni** [comment]
LGTM! very nice!

**Comment by mosheavni** [comment]
logs feature is 10000 times better now than it was before! amazing work.

**Pull request merged**
