### PR TITLE
Feat/native kubectl edit

### PR DESCRIPTION
**Pull request by mosheavni**
fixes: #214 
Kubectl edit using nvim editor, no inception.
I think it's nice what I got so far:

Currently pending:

- [x] when closing the yaml file, it closes vim instead of going back to the previous view
- [x] implement `kubectl patch -f` to apply changes

@Ramilito would love your input here

### CODE REVIEW

**Comment by Ramilito** [comment]
>  when closing the yaml file, it closes vim instead of going back to the previous view

I think you either add a key mapping that overrides `q` that only closes the buffer instead of the window. Or, open a floating buffer before you load the content, that would be similar to the current way we do it for describing a resource.

It's looking really good in the gif!

**Comment by mosheavni** [comment]
> > when closing the yaml file, it closes vim instead of going back to the previous view
> 
> I think you either add a key mapping that overrides `q` that only closes the buffer instead of the window. Or, open a floating buffer before you load the content, that would be similar to the current way we do it for describing a resource.
> 
> It's looking really good in the gif!

creating a `cmap` for `:q` and `:wq` makes the command line hang and act weird.
I'm looking for a better way

**Comment by mosheavni** [comment]
I decided to use a vsplit instead of changing the current buffer. it's working.
@Ramilito  maybe you want to move stuff around before we merge?

**Comment by Ramilito** [comment]
I'd rather have a floating buffer for this, do you see any issues with that?

**Comment by mosheavni** [comment]
> I'd rather have a floating buffer for this, do you see any issues with that?

I'm not against trying. wanna give the code a go?

**Comment by Ramilito** [comment]
> > I'd rather have a floating buffer for this, do you see any issues with that?
> 
> 
> 
> I'm not against trying. wanna give the code a go?

I'll give it a try later tonight!

**Comment by Ramilito** [comment]
Did some small changes:
- use the normal floating buffer as we use for the other operations.
- remove the temp file handling and just use in-memory, I believe it makes it easier and opens up another way for us to actually do an apply instead of being forced to save the buffer.

How about replacing the autocommands with a simple keybinding to apply the change? Not sure what's best there, we could also just mimic a "file save" if we think that's the best one

**Comment by mosheavni** [comment]
image

few issues:
- [ ] no line numbers, no relative line numbers
- [ ] filetype should be "yaml" so yaml-ls would start
- [ ] yaml-ls works on actual files, so when the buffer is not saved, there's no completion.

Really editing a kubernetes yaml without schema completion is pointless for me.

**Comment by mosheavni** [comment]
> Ah, mb, is that a hard requirement from lsp to have a real file? If so, we should revert the in memory one (I can fix that), we could still float it I'm sure by changing the vim.cmd to an edit instead of vsplit

Thanks. the float is a bit less intuitive for editing files. we better have a real file like `kubectl edit` does.

**Comment by mosheavni** [comment]
Added a conditional for when there's no namespace.
c7e9d13ee41018f40158d18a8d14f490379027a7

**Comment by Ramilito** [comment]
I'm not super into the vsplit way and floating buffer doesn't seem to play well either (too much manual work like attaching lsp and copying buffer config to mimic a normal buffer)

Went back to the original plan, we open a new tab and use a full view buffer, I think that solves your initial issues with exiting the buffer without closing the plugin.

Other minor changes:
- We fail hard if no temp file was created since that's not recoverable
- changed how we track modified to what I felt was a bit simpler (we track file modified time instead), only ugly thing was the defer_fn to allow for :wq to go through before checking.


What do you think?

**Comment by mosheavni** [comment]
oh my god better than I could have achieved. I love it!! let's merge it fast 🤩

**Pull request merged**
