### PR TITLE
feat: confirm before deletion

### PR DESCRIPTION
**Pull request by kezhenxu94**
For deletion operations I believe users should be prompted to avoid mistakes

### CODE REVIEW

**Comment by Ramilito** [comment]
Hey! Thanks for taking time for this PR 🙏

While I agree with the pods, the port forward seems a bit too overly protective?

**Comment by kezhenxu94** [comment]
> Hey! Thanks for taking time for this PR 🙏
> 
> While I agree with the pods, the port forward seems a bit too overly protective?

OK, reverted the one for PF

**Review by Ramilito — APPROVED** [review]

**Comment by Ramilito** [comment]
LGTM! 🚀

**Pull request merged**
