### PR TITLE
feat: update pum position

### PR DESCRIPTION
**Pull request by mosheavni**
move pum window as we type
a little buggy but gives better experience

### CODE REVIEW

**Comment by mosheavni** [comment]
fixed the bug with vim.schedule

**Comment by Ramilito** [comment]
Hmm I don't super like this and dont think I've seen that anywhere, it's jumping around a lot

**Comment by mosheavni** [comment]
Haha i thought you're gonna like it. Can we make it optional in the config? I for example see alot of benefit here

**Comment by Ramilito** [comment]
Haha it's cool but not for me 😅, but sure put it behind an autocomplete config table 👍

**Comment by mosheavni** [comment]
@Ramilito  made it optional. thanks!

**Review by Ramilito — APPROVED** [review]

**Pull request merged**
