### PR TITLE
feat: aliases view

### PR DESCRIPTION
**Pull request by Ramilito**
Solves #135 and parts of #23

Adds an alias search pop with tab autocomplete.
Choosing one will load that view.
If we have support for the view, that will be loaded otherwise a fallback view (generic view) with basic functionality (describe, edit, delete)

aliases

### CODE REVIEW

**Comment by mosheavni** [comment]
Does every <kbd><C-a></kbd> reloads the api-resources?
I'm not sure the flag `--cached` is working for me, hitting <kbd><C-a></kbd> is kinda slow every time.

**Comment by Ramilito** [comment]
Hmm I was hoping the cached would solve the performance tbh, running my own test seems to be performant, could you try running these commands?
```
time kubectl api-resources --cached
```
```
time kubectl api-resources
```

For me, the difference is almost 150ms so it seems to be doing something, the timing inside the plugin is also similar in loading time, from:
Execution time: 0.086942375 seconds  <- with cached
Execution time: 0.176638708 seconds   <- without cached

**Comment by mosheavni** [comment]
> Hmm I was hoping the cached would solve the performance tbh, running my own test seems to be performant, could you try running these commands?
> 
> ```
> time kubectl api-resources --cached
> ```
> 
> ```
> time kubectl api-resources
> ```
> 
> For me, the difference is almost 150ms so it seems to be doing something, the timing inside the plugin is also similar in loading time, from: Execution time: 0.086942375 seconds <- with cached Execution time: 0.176638708 seconds <- without cached

i have a cluster with many CRDs, a heavy cluster.
it gives me:

```
kubectl api-resources --cached  0.24s user 0.07s system 15% cpu 1.996 total
```

for me it's noticable for a window that should open very quick (maybe also rendering the float takes time)

I think it's better to keep an in-memory cache (`M.cached_api_resources = {...}`)

**Comment by Ramilito** [comment]
Added a new issue: #139

**Pull request merged**
