### PR TITLE
feat: add completion to filter

### PR DESCRIPTION
**Pull request by Ramilito**
added completion to filter
exclude namespace from filter

solves #286

### CODE REVIEW

**Comment by mosheavni** [comment]
very nice! any idea why it sends me to the start of the line upon completion?

**Comment by Ramilito** [comment]
hmm where are you seeing that? after filtering?

**Comment by Ramilito** [comment]
ah, that's probably `vim.api.nvim_win_set_cursor(0, { #header + 2, #prompt })`
We should check if cursor already is in prompt before calling that, it's supposed to help you when you select an option instead of using completion

**Comment by Ramilito** [comment]
fixed in #294

**Pull request merged**
