### PR TITLE
Feat/scale workloads

### PR DESCRIPTION
**Pull request by mosheavni**
for a lack of a better keymap, I used <kbd>\<C-s></kbd> for scaling deployments

### CODE REVIEW

**Comment by Ramilito** [comment]
lol finally, I've been doing ge then go to line 15 and then save for ever when testing stuff 😅 
How about `gs` as a binding instead? I'm thinking of keeping the ctrl bindings for other stuff

**Comment by mosheavni** [comment]
> lol finally, I've been doing ge then go to line 15 and then save for ever when testing stuff 😅 How about `gs` as a binding instead? I'm thinking of keeping the ctrl bindings for other stuff

`gs` is for sorting :)

**Comment by Ramilito** [comment]
Lol been a long day 😅

**Comment by Ramilito** [comment]
Ready to merge?

**Comment by mosheavni** [comment]
> Ready to merge?

yes

**Pull request merged**
