### PR TITLE
feat: add debug command to container

### PR DESCRIPTION
**Pull request by Ramilito**
Fixes: #463 
@mosheavni This is working pretty smooth, any suggestions for improvements?

### CODE REVIEW

**Comment by mosheavni** [comment]
I always want to be able to choose the image, busybox is very limited

**Comment by Ramilito** [comment]
Added prompt for image name but while testing it I found out that the ephemeral containers stick around even after the session terminates and it seems to be intentional for audit purposes according to discussions in Kubernetes github.

How do you work around that? Right now you can only debug once per container basically and then need to restart the pod

**Comment by mosheavni** [comment]
how do you see it? can you send a screenshot?
from the docs, it's not possible to do anything with the ephemeral container once created so not something that should bother us.
kubernetes users should take that into consideration before creating them.

I'd make the image selection as a float like the drain node float, just to keep consistency, but all in all looks great.

**Comment by Ramilito** [comment]
> how do you see it? can you send a screenshot? from the docs, it's not possible to do anything with the ephemeral container once created so not something that should bother us. kubernetes users should take that into consideration before creating them.
> 
> I'd make the image selection as a float like the drain node float, just to keep consistency, but all in all looks great.

This is the pod after you have created and exited a debug session:

image

And this is the second time you try to connect:
image


Maybe we just need to add the option to set the debug container name, that would at least remove the need to restart the pod for a new debug session

**Comment by mosheavni** [comment]
maybe we can add the ephemeral container to the container float that way we could click `<CR>` and easily exec back into it?

**Comment by Ramilito** [comment]
Hmm that's an interesting idea

**Pull request merged**
