### PR TITLE
docs: update keymaps

### PR DESCRIPTION
**Pull request by mosheavni**
Rearrange keymaps on readme and add view_6 for ingresses

@Ramilito  I think we're ready for v1.0.0 and a BIG announcement on reddit and [TWIN](https://dotfyle.com/this-week-in-neovim)

### CODE REVIEW

**Comment by Ramilito** [comment]
Yeah I'll try to get out an announcement today, I feel that this almost has all features that are needed for a V1 👍

**Review by Ramilito — APPROVED** [review]

**Comment by mosheavni** [comment]
> Yeah I'll try to get out an announcement today, I feel that this almost has all features that are needed for a V1 👍

indeed it does.
some small bugs, some missing stuff but in general it's much more usable than ever. People should start using it more and give us some feedback.
I have couple of teammates that are also using nvim as their main editor and use `k9s` regularly to switch to `k8s`, waiting for feedback from them as well.
Nice work and effort from both of us. Kudos!

**Comment by Ramilito** [comment]
Yeah and those small bugs are no showstoppers.

> Nice work and effort from both of us. Kudos!

It's been A LOT of work and I must say that the results have been something to be proud of ❤️, tbh I feel like this is even better than k9s in a lot of ways

**Comment by mosheavni** [comment]
> Yeah and those small bugs are no showstoppers.
> 
> > Nice work and effort from both of us. Kudos!
> 
> It's been A LOT of work and I must say that the results have been something to be proud of ❤️, tbh I feel like this is even better than k9s in a lot of ways

No doubt about that, far more intuitive, faster, even looks better!
this is why I am contributing to this project, It's a really useful tool for me as a DevOps engineer

**Comment by Ramilito** [comment]
Same here, really wanted this product my self for work, didn't think it would get this good though

**Comment by mosheavni** [comment]
> Same here, really wanted this product my self for work, didn't think it would get this good though

I think there are some game changers here, mainly the informer which is an incredible feature of kubernetes and you integrated it very nicely

**Comment by mosheavni** [comment]
@Ramilito  do you want have a better way of communication between me and you? A messaging platform of some sort? I feel communicating with comments here is not enough 😄

**Comment by Ramilito** [comment]
Sure thing! what platforms do you suggest?

**Comment by Ramilito** [comment]
> I think there are some game changers here, mainly the informer which is an incredible feature of kubernetes and you integrated it very nicely

Just having neovim as the UI is also such a game changer

**Comment by mosheavni** [comment]
> Sure thing! what platforms do you suggest?

we can use the kubernetes slack:
https://communityinviter.com/apps/kubernetes/community
Find me there: Moshe Avni

**Pull request merged**
