### PR TITLE
Feat/kubectl versions

### PR DESCRIPTION
**Pull request by mosheavni**
version is aligned:
image

version has a skew if 1 minor
image

version has a skew of more than 1 minor
image

### CODE REVIEW

**Comment by mosheavni** [comment]
@Ramilito i won't work on it until Sunday if maybe. If you feel like you can finish it, go ahead, if not all good 🙏🏼

**Comment by Ramilito** [comment]
I'll leave it until you return! Wanted to take a look at the #130 and see if there is something smart we can do there.

**Comment by mosheavni** [comment]
image
better looking separator.

**Comment by mosheavni** [comment]
I fixed a bug where you had context off, hints off, versions off and heartbeat on, the extmark would fail for end_row index out of range.
(this bug also exists on main)
32c0e6c

**Comment by mosheavni** [comment]
READY. @Ramilito

**Comment by Ramilito** [comment]
LGTM!
Awesome work Moshe!

**Review by Ramilito — APPROVED** [review]

**Pull request merged**
