### PR TITLE
fix: flickering colors

### PR DESCRIPTION
**Pull request by Ramilito**
Seems to be a bad idea to schedule extmarks in favor of faster data to the reader since it will cause flickering in colors as mentioned #262.

Bonus:
- Noticed that pretty_print was taking ~10ms at 600+ pods, we don't really do that much work, managed to refactor it down to ~3ms.
- Moved schedule to wrap whole setcontent

### CODE REVIEW

**Comment by mosheavni** [comment]
Amazing
How did you calculate the benchmark of pretty print?

**Comment by Ramilito** [comment]
> Amazing How did you calculate the benchmark of pretty print?

I'm using two ways, the easiest is just to use the timeme utility we have in utils/timeme.lua and surround a function with timeme.start()
.....
timeme.stop()

This just prints out the time in seconds and works great when you know where you need to improve.

The second way is how I usually start from, using the plugin: "stevearc/profile.nvim"
It gives me this view:

Before:
image

After:
image

**Comment by mosheavni** [comment]
Awesome! I'll start using that on my PRs :)
thank you for the detailed explanation.

**Comment by Ramilito** [comment]
I'm hoping this solves the flickering and gives us a snappier ui!

**Pull request merged**
