### PR TITLE
Feat/toggle headers

### PR DESCRIPTION
**Pull request by mosheavni**
Add keymaps to toggle the headers ad-hoc.
Sometimes I just want to hide the headers instead of going to the config and disabling and then re-enabling.
Add some simple mappings to toggle the headers with the option/alt key

### CODE REVIEW

**Comment by Ramilito** [comment]
I like it but how about just one keymap that toggles the whole header?

**Comment by mosheavni** [comment]
Done. do you like it better?

**Review by Ramilito — APPROVED** [review]

**Comment by Ramilito** [comment]
I love it!

**Pull request merged**
