### PR TITLE
fix: job view params

### PR DESCRIPTION
**Pull request by Ramilito**
Refactor so we don't need to send params into the draw function
Added filter helper

Need to reset the filter from job view

### CODE REVIEW

**Comment by mosheavni** [comment]
nice!

**Comment by mosheavni** [comment]
image

**Comment by Ramilito** [comment]
huh, that's weird, are there jobs without ownerreferences...I guess you can create a job directly, I'll add a nil check!

**Comment by Ramilito** [comment]
Should work better now!

**Pull request merged**
